title = "Redd Tsai"
baseURL = "https://reddtsai.github.io"
languageCode = "zh-tw"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
#googleAnalytics = ""
#enableRobotsTXT = true
disqusShortname = "reddtsai"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon-16x16.ico"
  #favicon = "favicon-32x32.ico"
  #description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "http://github.com/reddtsai"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/wholelife.jpg"
  recent_posts_number = 5
  commentoEnable = true
